### ISSUE TITLE
functors, applicatives, monads?

### ISSUE THREAD

**Issue by toraritte** [hdgarrood/purescript-numeric-hierarchy-guide#16]
First of all, thank you so much for all your efforts! This guide fills the gap to help get through the steep learning curve when someone is interested in math but doesn't know where to start.

 Are you planning to write a guide about functors, applicatives, monads?

I know that this guide is about explaining the nuanced approach Purescript takes in numeric types as opposed to Haskell but here's what gets me confused (and maybe others too): I started reading a lot of Haskell tutorials alongside the Purescript book and usually I ended up googling for an hour after a paragraph or half. I have a mental image of what functors etc. are and I think the Purescript book does the best job so far in showing real-world examples of abstract ideas (e.g., form validation using applicative functors) with being very consistent at the same time but it is still pretty dense for someone without a solid math background. Plus none of these guides go into deeper explanations ( and why would they?) on how these abstract ideas fit together: what are functors, monads etc? Are they a different field of math than numeric types? These questions probably don't make sense and it just shows the confusion in my head. I also understand that with time one will learn how to use these concepts intuitively. 

Sorry for the long note and thanks again!

**Comment by hdgarrood** [comment]
You're welcome :)

I don't have any plans to write something similar to this for the functor-applicative-monad hierarchy right now. The main reason for this is that they do indeed come from a different field of mathematics — the numeric classes come from abstract algebra, and the F-A-M classes come from category theory — and I unfortunately don't know very much about category theory. However, I did come across a series written by Bartosz Milewski called [Category Theory for Programmers](https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface/) which might be exactly what you're looking for (although I haven't read it yet, so I'm not sure).

**Comment by toraritte** [comment]
Thanks for the link! I'm probably just frustrated and building intuition takes time. Although one of your sentences helped me a lot to put things into their respective boxes (num -> abstract algebra, FAM -> category theory) :) Thanks for the prompt reply!
