### ISSUE TITLE
Confusing text in Groups chapter

### ISSUE THREAD

**Issue by ianp** [hdgarrood/purescript-numeric-hierarchy-guide#20]
In the section n Symmetric Groups it says

> Clearly, then, this set has _n_ elements.
> 
> This is a very important group so it has a name: it is called the _symmetric group of degree n._ We denote this group by _Sn_.

But then the section on Abelian Groups ends with

>  In fact, the symmetric group of degree 3, that is _S3,_ has exactly 6 elements.

This confused the hell out of me! Is it really correct?

**Comment by hdgarrood** [comment]
This is my fault for not being careful enough to distinguish the set {1,2,3,...,n}, which does indeed have n elements, from the group S_n, whose elements are permutations on that set. The group S_n has n! elements, so eg S_3 has 3 * 2 * 1 = 6 elements.

**Comment by ianp** [comment]
Ah! That makes sense, thanks for clarifying that 🙂

**Comment by hdgarrood** [comment]
I'm going to leave this open if that's alright, as a reminder to rewrite that section slightly to avoid this happening with other people.

**Comment by ianp** [comment]
Sure. And great work on this by the way, as someone who didn't cover stuff like this back in school/uni I'm finding it to be a really good introduction!

**Comment by hdgarrood** [comment]
I'm really glad to hear that, thanks for letting me know. :)
