### ISSUE TITLE
Make modular arithmetic `am` pattern more obvious

### ISSUE THREAD

**Issue by JordanMartinez** [hdgarrood/purescript-numeric-hierarchy-guide#22]
In the Groups section, talking about modular arithmetic, it reads...
> We say that x is congruent to y modulo m if and only if x−y is a multiple of m. In mathematical notation:
>
> x≡y(modm)⇔∃a∈Z.x−y=am
>
> For example, we will take m=12. Then, 15 is congruent to 3 modulo 12, because 15−3=12. 
> Also, 27 is congruent to 3 modulo 12, because 27−3=24=2×12

However, the first example doesn't follow the approach you mentioned before (`x - y` is a multiple of `m`). Perhaps this should read "`15 - 3 = (1 x 12) = 12`" or "`15 - 3 = 12 = (1 x 12)`" It makes the 'pattern' more obvious when one sees the second example concerning 27, 3, and 12.

Likewise
> By contrast, 2 is not congruent to 1 modulo 12, because `2−1=1` and 1 is not an integer multiple of 12.

... could add the following idea: "1 is not an integer multiple of 12 (e.g. `(1 x 12) != 1`, `(2 x 12) != 1`, etc.)"

Since this is a largely trivial thing and I'm sure you got better things to spend your time on, would you mind if I submit a PR that adds this?

**Comment by JordanMartinez** [comment]
Nevermind about the PR, just saw your point about the copyright stuff.

**Comment by hdgarrood** [comment]
Thanks for the report, but I'm actually tempted to leave this as-is. I think there's a risk you can over-explain and make people think there is more to something than there actually is. For this kind of writing, I think it's normal to have to reread a given paragraph a few times before you understand it, even, and I don't think that's really such a bad thing.

**Comment by JordanMartinez** [comment]
Good points!
