### ISSUE TITLE
Clarify how to read `a∈b¯¯¯` when `m=12`

### ISSUE THREAD

**Issue by JordanMartinez** [hdgarrood/purescript-numeric-hierarchy-guide#23]
In Groups > Modular Arithmetic

> We will define x¯¯¯ to be this set; that is:
>
> x¯¯¯={y∈Z|x≡y(mod m)}
>
> The set x¯¯¯ is called the congruence class of x.
>
> In particular, when m=12, we have seen that 15∈3¯¯¯, and 27∈3¯¯¯, but 2∉1¯¯¯.

It wasn't immediately obvious what `15∈3¯¯¯`, `27∈3¯¯¯`, and `2∉1¯¯¯` meant. Does 15 replace the `x` or the `y` in the definition?

Rather, I had to scroll up, remember how the calculations worked and then inferred that
`a∈b¯¯¯` meant `{b∈Z|a≡b(mod m)}` where `m=12`.

My confusion is partly because I wasn't sure whether the `x¯¯¯` refers to the `x` or the `y` in `x¯¯¯={y∈Z|x≡y(mod m)}`

**Comment by hdgarrood** [comment]
15 replaces the y in the definition: if you go back to the sentence where I introduce set-builder notation, it suggests understanding x̅  as "the set of y in ℤ such that x is congruent to y modulo m". If I then say that 15 is a member of the set 3̅  , I'm saying that 15 is one such y.

> Rather, I had to scroll up, remember how the calculations worked and then inferred that
a∈b¯¯¯ meant {b∈Z|a≡b(mod m)} where m=12.

This isn't quite how I would put it. `a ∈ b̅ ` means that `a ∈ { y ∈ ℤ | y ≡ b(mod m) }`, which is the same as  `a ≡ b(mod m)`. In particular, `a ∈ b̅ ` is a statement, whereas `{b∈Z|a≡b(mod m)}` is a set.

**Comment by hdgarrood** [comment]
Does that help? It's not quite clear to me how this section could be improved at the moment.

**Comment by JordanMartinez** [comment]
Yes it does. I was looking at the `x̅` idea as a function where I could replace certain parts of the function body with the function's argument (e.g. if `f(x) = x + 3`, then `f(4) = 4 + 3` == `7`). In such a situation, I saw `3¯¯¯` as a sort of function and wasn't sure what parts of the "body" it would replace.
