### ISSUE TITLE
Inexact definition of non-invertible functions

### ISSUE THREAD

**Issue by fbbdev** [hdgarrood/purescript-numeric-hierarchy-guide#27]
In the page about groups, section 'Permutations', subsection 'Surjectivity', the second statement reads:

> That is, if there’s no element y in the codomain such that f(x)=y for some x in the domain, we can’t invert it, because we don’t have anything to send y to.

The antecedent here implies, but is not equivalent to, non-surjectivity. So the statement is correct in itself, but I suspect it does not convey the intended meaning.
Also, it could be quite confusing to non-experts as the opening of the sentence sounds like a contradiction of the previous sentence (though it is not).

May I suggest

> there’s some element y in the codomain such that for no x in the domain f(x)=y

BTW many thanks for this clear, accessible and interesting piece. I'm not particularly interested in purescript, but I was looking for a simple yet rigorous introduction to algebraic structures, and here it is. Thank you.

**Comment by hdgarrood** [comment]
Yes, you're absolutely right, thank you! I'm glad to hear you found this useful.
