### ISSUE TITLE
Confusing lead-up question regarding _congruent class_

### ISSUE THREAD

**Issue by gomain** [hdgarrood/purescript-numeric-hierarchy-guide#28]
In the paragraph that reads..

> Now, we ask: given some integer x∈Z, and a modulus m∈Z,m>0, can we find the entire set of integers which are congruent to x modulo m? For example, can we find the entire set of integers congruent to 0 modulo 12?

I understood the last sentence to be "can we find the entire set of integers _**that are**_ congruent to 0 modulo 12?", i.e. the set { x ∈ Z | x ≡ 0 (mod 12) } which would be { 0, 12 , 24, ... }.

Then you go on and write

>{ y ∈ Z | x ≡ y (mod m ) }
>
>Read: “the set of y in Z such that x is congruent to y modulo m“.

I think the lead-up question may have been like "can we find the entire set of integers such that 0 would be congruent to _it_ modulo 12?" i.e. { x ∈ Z | 0 ≡ x (mod 12) } which would be { 0 } &mdash; does this even make sense?

**Comment by hdgarrood** [comment]
Does it help clear things up if I tell you that these two things are the same set?

* { x ∈ Z | 0 ≡ x (mod 12) }
* { x ∈ Z | x ≡ 0 (mod 12) }

**Comment by gomain** [comment]
They are indeed the same! They, both, are { ... -24, -12, 0, 12, 24, ... }, correct? (I wasn't considering negative *a*s earlier :frowning: )

So for x, y, m ∈ Z, with m > 0. The set { x | x ≡ y (mod m) } is the same set as  { x | y ≡ x (mod m) }. Because x &ndash; y is the *additive inverse* of y &ndash; x.

And therefor, x¯¯¯= { y ∈ Z | x ≡ y (mod m) } = { y ∈ Z | y ≡ x (mod m) }, for some m, correct?

**Comment by gomain** [comment]
So is there a reason to prefer { y ∈ Z | x ≡ y (mod m) } notation over { y ∈ Z | y ≡ x (mod m) } notation? The later would resonate with the lead-up question more?

**Comment by hdgarrood** [comment]
I don't think so - I don't really see that there's any real difference between them, since "is congruent to" is a symmetric relation - that is, "x is congruent to y" means exactly the same thing as "y is congruent to x".

**Comment by gomain** [comment]
Maybe you could add in this extra information. That congruence is symmetric. Maybe as an exercise to prove it.

**Comment by hdgarrood** [comment]
Yeah, that's a good idea, thanks!
