### ISSUE TITLE
Proof of 5.4 (vector R2 property) makes use of multiplication commutativeness in R

### ISSUE THREAD

**Issue by gomain** [hdgarrood/purescript-numeric-hierarchy-guide#29]
In the [proof](https://a-guide-to-the-purescript-numeric-hierarchy.readthedocs.io/en/latest/appendix/solutions/matrices/ex4.html) of (k<sub>1</sub>**x**)⋅(k<sub>2</sub>**y**) = k<sub>1</sub>k<sub>2</sub>(**x**⋅**y**) the third step reduces (k<sub>1</sub>x<sub>1</sub>)(k<sub>2</sub>y<sub>1</sub>)+(k<sub>1</sub>x<sub>2</sub>)(k<sub>2</sub>y<sub>2</sub>) = k<sub>1</sub>k<sub>2</sub>(x<sub>1</sub>y<sub>1</sub>+x<sub>2</sub>y<sub>2</sub>). This implies (k<sub>1</sub>x<sub>1</sub>)(k<sub>2</sub>y<sub>1</sub>) = (k<sub>1</sub>k<sub>2</sub>)(x<sub>1</sub>y<sub>1</sub>) and (k<sub>1</sub>x<sub>2</sub>)(k<sub>2</sub>y<sub>2</sub>) = (k<sub>1</sub>k<sub>2</sub>)(x<sub>2</sub>y<sub>2</sub>). Is it correct to assume R a *commutative ring*? &mdash; that this property only holds for vector of commutative rings.

**Comment by hdgarrood** [comment]
Yes, R is a commutative ring. The previous chapter did say this, although in a way that's quite easy to miss: part of the way through the previous chapter, I said "all the rings we've seen so far are commutative", and one of the rings we had seen by that point was R.

**Comment by gomain** [comment]
I was under the impression that, here, R represents instance of a *ring*.

**Comment by gomain** [comment]
Thank you :heart:

**Comment by hdgarrood** [comment]
Ahhh, I see - when people use a normal R then that usually means some abstract ring, yes, but ℝ means a specific ring: the real numbers. However, when you're typing it's often too much effort to work out how to type an ℝ so people often just use R when they really mean ℝ; I did this in my previous comment.

**Comment by gomain** [comment]
I wasn't confused that ℝ is *real numbers*. I just didn't expect that it be considered a *commutative ring*. Since it was only mentioned as a side note and we are continuing from *ring*.

Maybe a proper section for commutative rings in the previous chapter or a reminder/hint in this one would help others.

**Comment by hdgarrood** [comment]
Oh right, okay then. I don’t really want to add a new section about commutative rings because I’m not sure there’s all that much to say about them  really, unless we want to start introducing some slightly more complex new concepts, which I don’t think are really necessary for what I want the guide to accomplish and I’d rather keep it shorter. I’d prefer to just state more explicitly which rings are commutative in the rings chapter.
