### ISSUE TITLE
Mistake in matrix multiplication

### ISSUE THREAD

**Issue by mksmtn** [hdgarrood/purescript-numeric-hierarchy-guide#31]
Thanks for the guide, a great read. I think I see a mistake in matrix multiplication. Looks like the fourth element in AB should be 14, not 6.
![Screenshot_20221112-183452_Firefox](https://user-images.githubusercontent.com/26743971/201479186-7293b538-026b-48b4-9916-357593ee5c00.jpg)
![Screenshot_20221112-183143_Firefox](https://user-images.githubusercontent.com/26743971/201479191-10ee164d-7419-4aef-a76d-e38090fbca1f.jpg)

**Comment by hdgarrood** [comment]
Good spot, thank you!
